apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/dongfang-sodu/ods-platform/backend:0.2.0
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: ods-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ods-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ods-secrets
                  key: JWT_SECRET
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ods-secrets
                  key: RABBITMQ_PASSWORD
            - name: JAVA_TOOL_OPTIONS
              value: -XX:MaxRAMPercentage=70 -XX:+UseG1GC
          resources:
            requests:
              cpu: 150m
              memory: 512Mi
            limits:
              cpu: 800m
              memory: 768Mi
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8080
      targetPort: http
