apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ods
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
