import { FormEvent, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api } from '../api/client'
import { PageHeader } from '../components/PageHeader'
import { demoProjects } from '../data/demo'
import type { Project, ProjectStatus } from '../types'

type FormState = Omit<Project, 'id' | 'updatedAt'>
const blank: FormState = { code: '', name: '', product: '', qg4: '', owner: '', team: '', acquisitionDepartment: '', status: 'Draft', milestone: '', description: '' }

export function ProjectFormPage() {
  const { id } = useParams(); const navigate = useNavigate(); const editing = Boolean(id)
  const [form, setForm] = useState<FormState>(blank); const [errors, setErrors] = useState<Partial<Record<keyof FormState, string>>>({}); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('')
  useEffect(() => { if (!id) return; const existing = demoProjects.find((project) => project.id === id); if (existing) { const { id: _id, updatedAt: _updatedAt, ...values } = existing; setForm(values) } else api.projects.get(id).then(({ id: _id, updatedAt: _updatedAt, ...values }) => setForm(values)).catch(() => setMessage('Project could not be loaded.')) }, [id])
  const setValue = <Key extends keyof FormState,>(key: Key, value: FormState[Key]) => setForm((current) => ({ ...current, [key]: value }))
  const submit = async (event: FormEvent) => { event.preventDefault(); const nextErrors: typeof errors = {}; const required = editing ? ['name', 'product', 'owner', 'team'] as const : ['name', 'code', 'product', 'qg4', 'owner', 'team', 'acquisitionDepartment'] as const; required.forEach((key) => { if (!form[key]?.trim()) nextErrors[key] = 'This field is required' }); setErrors(nextErrors); if (Object.keys(nextErrors).length) return; setSaving(true); setMessage(''); try { if (id) await api.projects.update(id, form); else await api.projects.create(form); navigate('/projects') } catch (error) { setMessage(error instanceof Error ? error.message : 'Project could not be saved.') } finally { setSaving(false) } }
  return <>
    <PageHeader eyebrow="Digital Project Management" title={editing ? 'Edit project' : 'Create new project'} description="Capture the QG4 context and ownership needed to keep delivery transparent." actions={<Link className="button ghost" to={editing ? `/projects/${id}` : '/projects'}>Cancel</Link>} />
    <form className="card form-card" onSubmit={submit} noValidate><div className="form-intro"><span className="required-mark">*</span> Required fields. A project cannot be deleted after it is created.</div><div className="form-grid"><Field label="Project name" value={form.name} error={errors.name} onChange={(value) => setValue('name', value)} placeholder="e.g. Highway Pilot Gen 3" required /><Field label="Project code" value={form.code} error={errors.code} onChange={(value) => setValue('code', value)} placeholder="e.g. XC-ADAS-24" required={!editing} disabled={editing} /><Field label="Product / domain" value={form.product} error={errors.product} onChange={(value) => setValue('product', value)} placeholder="e.g. ADAS" required /><Field label="QG4 reference" value={form.qg4} error={errors.qg4} onChange={(value) => setValue('qg4', value)} placeholder="e.g. QG4-2025-001" required={!editing} disabled={editing} /><Field label="Project owner" value={form.owner} error={errors.owner} onChange={(value) => setValue('owner', value)} placeholder="Name or corporate ID" required /><Field label="Project team" value={form.team} error={errors.team} onChange={(value) => setValue('team', value)} placeholder="e.g. XC-AS Delivery" required /><Field label="Acquisition department" value={form.acquisitionDepartment} error={errors.acquisitionDepartment} onChange={(value) => setValue('acquisitionDepartment', value)} placeholder="e.g. SCP" required={!editing} disabled={editing} /><Field label="Milestone date" type="date" value={form.milestone} error={errors.milestone} onChange={(value) => setValue('milestone', value)} /><label className="field"><span>Status</span><select value={form.status} onChange={(event) => setValue('status', event.target.value as ProjectStatus)}>{(['Draft', 'Active', 'On hold', 'Completed', 'Cancelled'] as ProjectStatus[]).map((value) => <option key={value}>{value}</option>)}</select></label><label className="field field-wide"><span>Description</span><textarea rows={5} value={form.description} onChange={(event) => setValue('description', event.target.value)} placeholder="Add context, scope and links for collaborators" /></label></div>{message && <div className="form-message error-message">{message}</div>}<div className="form-actions"><Link className="button ghost" to={editing ? `/projects/${id}` : '/projects'}>Cancel</Link><button className="button primary" disabled={saving}>{saving ? 'Saving…' : editing ? 'Save project' : 'Create project'}</button></div></form>
  </>
}

function Field({ label, value, error, onChange, placeholder, required, disabled, type = 'text' }: { label: string; value: string; error?: string; onChange: (value: string) => void; placeholder?: string; required?: boolean; disabled?: boolean; type?: string }) { return <label className={`field ${error ? 'has-error' : ''}`}><span>{label}{required && <em> *</em>}</span><input type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} disabled={disabled} />{error && <small className="field-error">{error}</small>}</label> }
